# Generated by Django 2.0.12 on 2020-05-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('baseprice', models.FloatField()),
                ('extraprice', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.FloatField()),
                ('topping', models.ManyToManyField(blank=True, related_name='carttopping', to='myapi.Topping')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='topping',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartitem',
            field=models.ManyToManyField(related_name='cartitem', to='myapi.CartItem'),
        ),
    ]
