# Generated by Django 2.0.12 on 2020-05-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200508_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cartitem',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
